#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Record_Unsafe::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Symbol::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Eq


#[derive(Clone)]
pub struct Dict_EqRecord {
    pub eqRecord: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>>
}

#[derive(Clone)]
pub struct Dict_Eq {
    pub eq: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>
}

#[derive(Clone)]
pub struct Dict_Eq1 {
    pub eq1: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>>
}

pub fn Data_Eq_eqVoid() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    drop(v1);
    /* Typed bool <- bool : Lit */true
})
}) }))
}

pub fn Data_Eq_eqUnit() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    drop(v1);
    /* Typed bool <- bool : Lit */true
})
}) }))
}

pub fn Data_Eq_eqString() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(String) -> std::rc::Rc<dyn Fn(String) -> bool>> <- std::rc::Rc<dyn Fn(String) -> std::rc::Rc<dyn Fn(String) -> bool>> : Var(...) */std::rc::Rc::new({ let _f = (crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {  crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType { let mut eta_0 = eta_0.clone(); crate::mk_bool(Data_Eq_eqStringImpl((eta_0.clone()).unwrap_string(), (eta_1.clone()).unwrap_string())) })) }))).unwrap_func(); move |mut _a: String| -> std::rc::Rc<dyn Fn(String) -> bool> { std::rc::Rc::new({ let _f = (_f(crate::mk_string(&(_a)))).unwrap_func(); move |mut _a: String| -> bool { (_f(crate::mk_string(&(_a)))).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eqRowNil() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { eqRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    drop(v1);
    /* Typed Abs */std::rc::Rc::new(move |mut v2: crate::UnknownType| -> bool {
    drop(v2);
    /* Typed bool <- bool : Lit */true
})
})
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(_a)) } })) } })) } }))), ..Default::default() }))
}

pub fn Data_Eq_eqRecord(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType, mut a3: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().eqRecord.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone()))(a3.clone())
}

pub fn Data_Eq_eqRec(mut _dollar___unused: crate::UnknownType, mut dictEqRecord: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- crate::UnknownType : App(Accessor(Local(...))) */std::rc::Rc::new({ let _f = ((dictEqRecord.unwrap_record().eqRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eqProxy() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    drop(v1);
    /* Typed bool <- bool : Lit */true
})
}) }))
}

pub fn Data_Eq_eqNumber() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(f64) -> std::rc::Rc<dyn Fn(f64) -> bool>> <- std::rc::Rc<dyn Fn(f64) -> std::rc::Rc<dyn Fn(f64) -> bool>> : Var(...) */std::rc::Rc::new({ let _f = (crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {  crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType { let mut eta_0 = eta_0.clone(); crate::mk_bool(Data_Eq_eqNumberImpl((eta_0.clone()).unwrap_number(), (eta_1.clone()).unwrap_number())) })) }))).unwrap_func(); move |mut _a: f64| -> std::rc::Rc<dyn Fn(f64) -> bool> { std::rc::Rc::new({ let _f = (_f(crate::mk_number(_a))).unwrap_func(); move |mut _a: f64| -> bool { (_f(crate::mk_number(_a))).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eqInt() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(i64) -> std::rc::Rc<dyn Fn(i64) -> bool>> <- std::rc::Rc<dyn Fn(i64) -> std::rc::Rc<dyn Fn(i64) -> bool>> : Var(...) */std::rc::Rc::new({ let _f = (crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {  crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType { let mut eta_0 = eta_0.clone(); crate::mk_bool(Data_Eq_eqIntImpl((eta_0.clone()).unwrap_int(), (eta_1.clone()).unwrap_int())) })) }))).unwrap_func(); move |mut _a: i64| -> std::rc::Rc<dyn Fn(i64) -> bool> { std::rc::Rc::new({ let _f = (_f(crate::mk_int(_a))).unwrap_func(); move |mut _a: i64| -> bool { (_f(crate::mk_int(_a))).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eqChar() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(char) -> std::rc::Rc<dyn Fn(char) -> bool>> <- std::rc::Rc<dyn Fn(char) -> std::rc::Rc<dyn Fn(char) -> bool>> : Var(...) */std::rc::Rc::new({ let _f = (crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {  crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType { let mut eta_0 = eta_0.clone(); crate::mk_bool(Data_Eq_eqCharImpl((eta_0.clone()).unwrap_char(), (eta_1.clone()).unwrap_char())) })) }))).unwrap_func(); move |mut _a: char| -> std::rc::Rc<dyn Fn(char) -> bool> { std::rc::Rc::new({ let _f = (_f(crate::mk_char(_a))).unwrap_func(); move |mut _a: char| -> bool { (_f(crate::mk_char(_a))).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eqBoolean() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(bool) -> std::rc::Rc<dyn Fn(bool) -> bool>> <- std::rc::Rc<dyn Fn(bool) -> std::rc::Rc<dyn Fn(bool) -> bool>> : Var(...) */std::rc::Rc::new({ let _f = (crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {  crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType { let mut eta_0 = eta_0.clone(); crate::mk_bool(Data_Eq_eqBooleanImpl((eta_0.clone()).unwrap_bool(), (eta_1.clone()).unwrap_bool())) })) }))).unwrap_func(); move |mut _a: bool| -> std::rc::Rc<dyn Fn(bool) -> bool> { std::rc::Rc::new({ let _f = (_f(crate::mk_bool(_a))).unwrap_func(); move |mut _a: bool| -> bool { (_f(crate::mk_bool(_a))).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eq1(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType, mut a3: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().eq1.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone()))(a3.clone())
}

pub fn Data_Eq_eq(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().eq.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Eq_eqArray(mut dictEq: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> : App(Var(...)) */std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- crate::UnknownType : Accessor(Local(...)) */std::rc::Rc::new({ let _f = (dictEq.unwrap_record().eq.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } });
    crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eta_0 = eta_0.clone();
    crate::mk_bool(Data_Eq_eqArrayImpl(eval_arg_0, eta_0.clone(), eta_1.clone()))
}))
}))
}).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } }) }))
}

pub fn Data_Eq_eq1Array() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq1 { eq1: /* Typed Abs */std::rc::Rc::new(move |mut dictEq: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> : App(Var(...)) */std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- crate::UnknownType : Accessor(Local(...)) */std::rc::Rc::new({ let _f = (dictEq.unwrap_record().eq.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } });
    crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eta_0 = eta_0.clone();
    crate::mk_bool(Data_Eq_eqArrayImpl(eval_arg_0, eta_0.clone(), eta_1.clone()))
}))
}))
}).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } })
}) }))
}

pub fn Data_Eq_eqRowCons(mut dictEqRecord: crate::UnknownType, mut _dollar___unused: crate::UnknownType, mut dictIsSymbol: crate::UnknownType, mut dictEq: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { eqRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    let mut dictEq = dictEq.clone();
    let mut dictEqRecord = dictEqRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    drop(v);
    /* Typed Abs */{
    let mut dictEq = dictEq.clone();
    let mut dictEqRecord = dictEqRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut ra: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    let mut dictEq = dictEq.clone();
    let mut dictEqRecord = dictEqRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    /* Typed Abs */{
    let mut dictEq = dictEq.clone();
    let mut dictEqRecord = dictEqRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut rb: crate::UnknownType| -> bool {
    let mut dictEq = dictEq.clone();
    let mut dictEqRecord = dictEqRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut ra = ra.clone();
    /* Typed bool <- bool : Let(...) */{
    let mut get = /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> <- std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> : App(Var(...)) */std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string();
    crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Record_Unsafe_unsafeGet(eval_arg_0, eta_0.clone())
}))
}).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } });
    /* Typed bool <- bool : PrimOp(...) */((((dictEq.clone().unwrap_record().eq.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(get.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone()))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(get)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb.clone()))).unwrap_bool() && /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */((((dictEqRecord.clone().unwrap_record().eqRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb)).unwrap_bool())
}
})
}
})
}
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(_a)) } })) } })) } }))), ..Default::default() }))
}

pub fn Data_Eq_notEq(mut dictEq: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(PrimOp(...))))))))))))
/* Typed bool <- bool : PrimOp(...) */!((((dictEq.unwrap_record().eq.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)).unwrap_bool() /* aTy: crate::UnknownType, a is App(Accessor(Local(...))), fn ty is Any, lvl_3 in bound: none, lvl_3 in arities: none */)
}

pub fn Data_Eq_notEq1(mut dictEq1: crate::UnknownType, mut dictEq: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(PrimOp(...))))))))))))))
/* Typed bool <- bool : PrimOp(...) */!(((((dictEq1.unwrap_record().eq1.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */dictEq)).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)).unwrap_bool() /* aTy: crate::UnknownType, a is App(Accessor(Local(...))), fn ty is Any, lvl_3 in bound: none, lvl_3 in arities: none */)
}



pub fn Data_Eq_eqIntImpl(mut a0: i64, mut a1: i64) -> bool {
    a0 == a1
}

pub fn Data_Eq_eqNumberImpl(mut a0: f64, mut a1: f64) -> bool {
    a0 == a1
}

pub fn Data_Eq_eqCharImpl(mut a0: char, mut a1: char) -> bool {
    a0 == a1
}

pub fn Data_Eq_eqStringImpl(mut a0: String, mut a1: String) -> bool {
    a0 == a1
}

pub fn Data_Eq_eqBooleanImpl(mut a0: bool, mut a1: bool) -> bool {
    a0 == a1
}

pub fn Data_Eq_eqArrayImpl(mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>, mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> bool {
    let arr1 = a0.unwrap_array();
    let arr2 = a1.unwrap_array();
    if arr1.len() != arr2.len() {
        return false;
    }
    for (x, y) in arr1.iter().zip(arr2.iter()) {
        let res = f(x.clone())(y.clone());
        if !res {
            return false;
        }
    }
    true
}




