[package]
name = "Purs_Effect_Class_Console"
version = "0.1.0"
edition = "2021"

[dependencies]
purust_core = { path = "../purust_core" }
perceus_ptr = { path = "/Users/0x1/Documents/htdocs/purust/purust/tests/runtime/perceus_ptr" }
fancy-regex = "0.13"
Purs_Effect_Console = { path = "../Purs_Effect_Console" }
Purs_Control_Applicative = { path = "../Purs_Control_Applicative" }
Purs_Control_Bind = { path = "../Purs_Control_Bind" }
Purs_Control_Semigroupoid = { path = "../Purs_Control_Semigroupoid" }
Purs_Effect_Class = { path = "../Purs_Effect_Class" }