#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;


// Code generated by purust for module Record_Unsafe





pub fn Record_Unsafe_unsafeDelete(mut a0: String, mut a1: crate::UnknownType) -> crate::UnknownType { UnknownType::new(Record_a { ..Default::default() }) }
pub fn Record_Unsafe_unsafeGet(mut a0: String, mut a1: crate::UnknownType) -> crate::UnknownType { UnknownType::new(Record_a { ..Default::default() }) }
pub fn Record_Unsafe_unsafeHas(mut a0: String, mut a1: crate::UnknownType) -> bool { false }
pub fn Record_Unsafe_unsafeSet(mut a0: String, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType { UnknownType::new(Record_a { ..Default::default() }) }


