#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Applicative::*;
use Purs_Control_Bind::*;
use Purs_Data_Show::*;
use Purs_Effect::*;

// Code generated by purust for module Effect_Console



pub fn Effect_Console_warnShow(mut dictShow: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Var(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_warn(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_string())
}

pub fn Effect_Console_logShow(mut dictShow: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Var(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_string())
}

pub fn Effect_Console_infoShow(mut dictShow: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Var(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_info(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_string())
}

pub fn Effect_Console_grouped(mut name: String, mut inner: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Let(...))))))))
{
    crate::Value::Func(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: Effect_Console_group, Effect_Console_groupEnd, inner, name
    let mut inner = inner.clone();
    let mut name = name.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut lvl_2 = Effect_Console_group(/* Typed String <- String : Local(...) */name.clone());
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut _dollar___unused = {
        let _val_eval = lvl_2;
        if let crate::Value::Func(f) = &_val_eval {
            f(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))
        } else if let crate::Value::Record(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    };
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut result = {
        let _val_eval = inner.clone();
        if let crate::Value::Func(f) = &_val_eval {
            f(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))
        } else if let crate::Value::Record(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    };
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut _dollar___unused = {
        let _val_eval = Effect_Console_groupEnd().clone();
        if let crate::Value::Func(f) = &_val_eval {
            f(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))
        } else if let crate::Value::Record(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    };
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : EffectPure */result
}
}
}
}
    }))
}
}

pub fn Effect_Console_errorShow(mut dictShow: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Var(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_error(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_string())
}

pub fn Effect_Console_debugShow(mut dictShow: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Var(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_debug(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_string())
}



use std::rc::Rc;
use crate::{UnknownType, Record_a};

pub fn Effect_Console_log(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            println!("{}", a0);
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_error(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            eprintln!("{}", a0);
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_warn(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            eprintln!("WARN: {}", a0);
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_info(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            println!("INFO: {}", a0);
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_debug(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            println!("DEBUG: {}", a0);
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_clear() -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_group(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_groupCollapsed(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_groupEnd() -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_time(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_timeEnd(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}

pub fn Effect_Console_timeLog(mut a0: String) -> UnknownType {
    crate::Value::Func(Rc::new(move |mut _u: UnknownType| -> UnknownType {
            crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
        }))
}




