#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Eq::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Show::*;

// Code generated by purust for module Data_Ordering

#[derive(Clone)]
pub enum Ordering {
    EQ,
    GT,
    LT
}


pub fn Data_Ordering_LT() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "LT", ..Default::default() }))
}

pub fn Data_Ordering_GT() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "GT", ..Default::default() }))
}

pub fn Data_Ordering_EQ() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "EQ", ..Default::default() }))
}

pub fn Data_Ordering_showOrdering() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    /* Typed String <- String : Branch(...) */if (v.clone().unwrap_record().tag == "LT") {
        /* Typed String <- String : Lit */String::from(r#"LT"#)
    } else if (v.clone().unwrap_record().tag == "GT") {
        /* Typed String <- String : Lit */String::from(r#"GT"#)
    } else if (v.unwrap_record().tag == "EQ") {
        /* Typed String <- String : Lit */String::from(r#"EQ"#)
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}) }))
}

pub fn Data_Ordering_semigroupOrdering() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semigroup::Dict_Semigroup { append: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if (v.clone().unwrap_record().tag == "LT") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "LT", vals: None, ..Default::default() }))
    } else if (v.clone().unwrap_record().tag == "GT") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "GT", vals: None, ..Default::default() }))
    } else if (v.clone().unwrap_record().tag == "EQ") {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
})
}) }))
}

pub fn Data_Ordering_invert(mut v: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Branch(...)))))
/* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if (v.clone().unwrap_record().tag == "GT") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "LT", vals: None, ..Default::default() }))
    } else if (v.clone().unwrap_record().tag == "EQ") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "EQ", vals: None, ..Default::default() }))
    } else if (v.unwrap_record().tag == "LT") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "GT", vals: None, ..Default::default() }))
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}

pub fn Data_Ordering_eqOrdering() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    let mut v = v.clone();
    /* Typed bool <- bool : Branch(...) */if (v.clone().unwrap_record().tag == "LT") {
        (v1.unwrap_record().tag == "LT")
    } else if (v.clone().unwrap_record().tag == "GT") {
        (v1.unwrap_record().tag == "GT")
    } else {
        ((v.clone().unwrap_record().tag == "EQ") && (v1.unwrap_record().tag == "EQ"))
    }
})
}) }))
}





