#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_Monoid::*;

// Code generated by purust for module Data_Monoid_Generic


#[derive(Clone)]
pub struct Dict_GenericMonoid {
    pub genericMempty_prime: crate::UnknownType
}

pub fn Data_Monoid_Generic_genericMonoidNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid_Generic::Dict_GenericMonoid { genericMempty_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() })) }))
}

pub fn Data_Monoid_Generic_genericMonoidArgument(mut dictMonoid: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid_Generic::Dict_GenericMonoid { genericMempty_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictMonoid.unwrap_record().mempty.clone().unwrap() }))
}

pub fn Data_Monoid_Generic_genericMempty_prime(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().genericMempty_prime.clone().unwrap()
}

pub fn Data_Monoid_Generic_genericMonoidConstructor(mut dictGenericMonoid: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid_Generic::Dict_GenericMonoid { genericMempty_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericMonoid.unwrap_record().genericMempty_prime.clone().unwrap() }))
}

pub fn Data_Monoid_Generic_genericMonoidProduct(mut dictGenericMonoid: crate::UnknownType, mut dictGenericMonoid1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid_Generic::Dict_GenericMonoid { genericMempty_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![dictGenericMonoid.unwrap_record().genericMempty_prime.clone().unwrap(), dictGenericMonoid1.unwrap_record().genericMempty_prime.clone().unwrap()])), ..Default::default() })) }))
}

pub fn Data_Monoid_Generic_genericMempty(mut dictGeneric: crate::UnknownType, mut dictGenericMonoid: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericMonoid.unwrap_record().genericMempty_prime.clone().unwrap())
}





