#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;

// Code generated by purust for module Data_Ord_Generic


#[derive(Clone)]
pub struct Dict_GenericOrd {
    pub genericCompare_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>
}

pub fn Data_Ord_Generic_genericOrdNoConstructors() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord_Generic::Dict_GenericOrd { genericCompare_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "EQ", vals: None, ..Default::default() }))
})
}) }))
}

pub fn Data_Ord_Generic_genericOrdNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord_Generic::Dict_GenericOrd { genericCompare_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "EQ", vals: None, ..Default::default() }))
})
}) }))
}

pub fn Data_Ord_Generic_genericOrdArgument(mut dictOrd: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord_Generic::Dict_GenericOrd { genericCompare_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictOrd = dictOrd.clone();
    /* Typed Abs */{
    let mut dictOrd = dictOrd.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictOrd = dictOrd.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictOrd.clone().unwrap_record().compare.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}) }))
}

pub fn Data_Ord_Generic_genericCompare_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Ord_Generic_genericOrdConstructor(mut dictGenericOrd: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord_Generic::Dict_GenericOrd { genericCompare_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericOrd = dictGenericOrd.clone();
    /* Typed Abs */{
    let mut dictGenericOrd = dictGenericOrd.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericOrd.clone().unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}) }))
}

pub fn Data_Ord_Generic_genericOrdProduct(mut dictGenericOrd: crate::UnknownType, mut dictGenericOrd1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord_Generic::Dict_GenericOrd { genericCompare_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut dictGenericOrd1 = dictGenericOrd1.clone();
    /* Typed Abs */{
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut dictGenericOrd1 = dictGenericOrd1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut dictGenericOrd1 = dictGenericOrd1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut v2 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericOrd.clone().unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone());
    if (v2.clone().unwrap_record().tag == "EQ") {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericOrd1.clone().unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v2
    }
}
})
}
}) }))
}

pub fn Data_Ord_Generic_genericOrdSum(mut dictGenericOrd: crate::UnknownType, mut dictGenericOrd1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord_Generic::Dict_GenericOrd { genericCompare_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut dictGenericOrd1 = dictGenericOrd1.clone();
    /* Typed Abs */{
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut dictGenericOrd1 = dictGenericOrd1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericOrd = dictGenericOrd.clone();
    let mut dictGenericOrd1 = dictGenericOrd1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if (v.clone().unwrap_record().tag == "Inl") {
        if (v1.clone().unwrap_record().tag == "Inl") {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericOrd.clone().unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[0].clone())
    } else if (v1.unwrap_record().tag == "Inr") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "LT", vals: None, ..Default::default() }))
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
    } else if (v.clone().unwrap_record().tag == "Inr") {
        if (v1.clone().unwrap_record().tag == "Inr") {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericOrd1.clone().unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[0].clone())
    } else if (v1.unwrap_record().tag == "Inl") {
        /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "GT", vals: None, ..Default::default() }))
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
})
}
}) }))
}

pub fn Data_Ord_Generic_genericCompare(mut dictGeneric: crate::UnknownType, mut dictGenericOrd: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...)))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericOrd.unwrap_record().genericCompare_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y))
}





