[package]
name = "Purs_Data_Monoid_Conj"
version = "0.1.0"
edition = "2021"

[dependencies]
purust_core = { path = "../purust_core" }
perceus_ptr = { path = "/Users/0x1/Documents/htdocs/purust/purust/tests/runtime/perceus_ptr" }
fancy-regex = "0.13"
Purs_Control_Applicative = { path = "../Purs_Control_Applicative" }
Purs_Control_Apply = { path = "../Purs_Control_Apply" }
Purs_Control_Bind = { path = "../Purs_Control_Bind" }
Purs_Control_Monad = { path = "../Purs_Control_Monad" }
Purs_Data_Eq = { path = "../Purs_Data_Eq" }
Purs_Data_Functor = { path = "../Purs_Data_Functor" }
Purs_Data_HeytingAlgebra = { path = "../Purs_Data_HeytingAlgebra" }
Purs_Data_Monoid = { path = "../Purs_Data_Monoid" }
Purs_Data_Ord = { path = "../Purs_Data_Ord" }
Purs_Data_Semigroup = { path = "../Purs_Data_Semigroup" }
Purs_Data_Semiring = { path = "../Purs_Data_Semiring" }
Purs_Data_Show = { path = "../Purs_Data_Show" }