[package]
name = "Purs_Data_Ordering"
version = "0.1.0"
edition = "2021"

[dependencies]
purust_core = { path = "../purust_core" }
perceus_ptr = { path = "/Users/0x1/Documents/htdocs/purust/purust/tests/runtime/perceus_ptr" }
fancy-regex = "0.13"
Purs_Data_Eq = { path = "../Purs_Data_Eq" }
Purs_Data_Semigroup = { path = "../Purs_Data_Semigroup" }
Purs_Data_Show = { path = "../Purs_Data_Show" }