#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Ring::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Semiring::*;

// Code generated by purust for module Data_DivisionRing


#[derive(Clone)]
pub struct Dict_DivisionRing {
    pub Ring0: crate::UnknownType,
    pub recip: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>
}

pub fn Data_DivisionRing_recip(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().recip.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_DivisionRing_rightDiv(mut dictDivisionRing: crate::UnknownType, mut a: crate::UnknownType, mut b: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Semiring0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(App(Accessor(Local(...))))) */((dictDivisionRing.clone().unwrap_record().Ring0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))).unwrap_record().Semiring0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Semiring0.unwrap_class::<crate::Purs_Data_Semiring::Dict_Semiring>().mul.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictDivisionRing.unwrap_record().recip.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */b))
}
}

pub fn Data_DivisionRing_leftDiv(mut dictDivisionRing: crate::UnknownType, mut a: crate::UnknownType, mut b: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Semiring0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(App(Accessor(Local(...))))) */((dictDivisionRing.clone().unwrap_record().Ring0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))).unwrap_record().Semiring0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Semiring0.unwrap_class::<crate::Purs_Data_Semiring::Dict_Semiring>().mul.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictDivisionRing.unwrap_record().recip.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */b))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)
}
}

pub fn Data_DivisionRing_divisionringNumber() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_DivisionRing::Dict_DivisionRing { recip: /* Typed Abs */std::rc::Rc::new(move |mut x: f64| -> f64 {
    /* Typed f64 <- f64 : PrimOp(...) */(1.0 / /* Typed f64 <- f64 : Local(...) */x)
}), Ring0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ring_ringNumber().clone()
}) }))
}





