#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Monad::*;
use Purs_Data_Eq::*;
use Purs_Data_Functor::*;
use Purs_Data_Ord::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Show::*;

// Code generated by purust for module Data_Semigroup_Last



pub fn Data_Semigroup_Last_Last(mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Abs(..., Local(...))
x
}

pub fn Data_Semigroup_Last_showLast(mut dictShow: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictShow = dictShow.clone();
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from(r#"(Last "#), ((dictShow.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v)).unwrap_string()), String::from(r#")"#))
}) }))
}

pub fn Data_Semigroup_Last_semigroupLast() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semigroup::Dict_Semigroup { append: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut x: crate::UnknownType| -> crate::UnknownType {
    /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x
})
}) }))
}

pub fn Data_Semigroup_Last_ordLast(mut dictOrd: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Local(...)))))
/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */dictOrd
}

pub fn Data_Semigroup_Last_functorLast() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Functor::Dict_Functor { map: /* Typed Abs */std::rc::Rc::new(move |mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    /* Typed Abs */std::rc::Rc::new(move |mut m: crate::UnknownType| -> crate::UnknownType {
    let mut f = f.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */m)
})
}) }))
}

pub fn Data_Semigroup_Last_eqLast(mut dictEq: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Local(...)))))
/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */dictEq
}

pub fn Data_Semigroup_Last_eq1Last() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq1 { eq1: /* Typed Abs */std::rc::Rc::new(move |mut dictEq: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- crate::UnknownType : Accessor(Local(...)) */std::rc::Rc::new({ let _f = (dictEq.unwrap_record().eq.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } })
}) }))
}

pub fn Data_Semigroup_Last_ord1Last() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord::Dict_Ord1 { compare1: /* Typed Abs */std::rc::Rc::new(move |mut dictOrd: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> <- crate::UnknownType : Accessor(Local(...)) */std::rc::Rc::new({ let _f = (dictOrd.unwrap_record().compare.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}), Eq10: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_Last_eq1Last().clone()
}) }))
}

pub fn Data_Semigroup_Last_boundedLast(mut dictBounded: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Local(...)))))
/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */dictBounded
}

pub fn Data_Semigroup_Last_applyLast() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Apply::Dict_Apply { apply: /* Typed Abs */std::rc::Rc::new(move |mut v: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(v.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}), Functor0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_Last_functorLast().clone()
}) }))
}

pub fn Data_Semigroup_Last_bindLast() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Bind::Dict_Bind { bind: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> crate::UnknownType> {
    /* Typed Abs */std::rc::Rc::new(move |mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> crate::UnknownType {
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())
})
}), Apply0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_Last_applyLast().clone()
}) }))
}

pub fn Data_Semigroup_Last_applicativeLast() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Applicative::Dict_Applicative { pure: /* Typed Abs */std::rc::Rc::new(move |mut x: crate::UnknownType| -> crate::UnknownType {
    x
}), Apply0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_Last_applyLast().clone()
}) }))
}

pub fn Data_Semigroup_Last_monadLast() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Monad::Dict_Monad { Applicative0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_Last_applicativeLast().clone()
}), Bind1: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_Last_bindLast().clone()
}) }))
}





