#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Unit::*;
use Purs_Record_Unsafe::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Ordering::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Boolean::*;
use Purs_Data_Eq::*;
use Purs_Data_Ord::*;
use Purs_Data_Symbol::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Monoid


#[derive(Clone)]
pub struct Dict_MonoidRecord {
    pub SemigroupRecord0: crate::UnknownType,
    pub memptyRecord: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>
}

#[derive(Clone)]
pub struct Dict_Monoid {
    pub Semigroup0: crate::UnknownType,
    pub mempty: crate::UnknownType
}

pub fn Data_Monoid_monoidUnit() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid::Dict_Monoid { mempty: /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Unit_unit(), Semigroup0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_semigroupUnit().clone()
}) }))
}

pub fn Data_Monoid_monoidString() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid::Dict_Monoid { mempty: /* Typed String <- String : Lit */String::from(r#""#), Semigroup0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_semigroupString().clone()
}) }))
}

pub fn Data_Monoid_monoidRecordNil() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { memptyRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }))
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), SemigroupRecord0: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_semigroupRecordNil().clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), ..Default::default() }))
}

pub fn Data_Monoid_monoidOrdering() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid::Dict_Monoid { mempty: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "EQ", vals: None, ..Default::default() })), Semigroup0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ordering_semigroupOrdering().clone()
}) }))
}

pub fn Data_Monoid_monoidArray() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid::Dict_Monoid { mempty: /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::mk_array(vec![]), Semigroup0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Semigroup_semigroupArray().clone()
}) }))
}

pub fn Data_Monoid_memptyRecord(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().memptyRecord.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_Monoid_monoidRecord(mut _dollar___unused: crate::UnknownType, mut dictMonoidRecord: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut semigroupRecord1 = crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semigroup::Dict_Semigroup { append: /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> <- crate::UnknownType : App(Accessor(App(Accessor(Local(...))))) */std::rc::Rc::new({ let _f = (((dictMonoidRecord.clone().unwrap_record().SemigroupRecord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))).unwrap_record().appendRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } }) }));
    crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid::Dict_Monoid { mempty: /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonoidRecord.unwrap_record().memptyRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() }))), Semigroup0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut semigroupRecord1 = semigroupRecord1.clone();
    drop(_dollar___unused);
    semigroupRecord1.clone()
}) }))
}
}

pub fn Data_Monoid_mempty(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().mempty.clone().unwrap()
}

pub fn Data_Monoid_monoidFn(mut dictMonoid: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut semigroupFn = /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut lvl_1 = (dictMonoid.clone().unwrap_record().Semigroup0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { append: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    let mut lvl_1 = lvl_1.clone();
    /* Typed Abs */{
    let mut lvl_1 = lvl_1.clone();
    std::rc::Rc::new(move |mut g: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut f = f.clone();
    let mut lvl_1 = lvl_1.clone();
    /* Typed Abs */{
    let mut f = f.clone();
    let mut lvl_1 = lvl_1.clone();
    std::rc::Rc::new(move |mut x: crate::UnknownType| -> crate::UnknownType {
    let mut f = f.clone();
    let mut g = g.clone();
    let mut lvl_1 = lvl_1.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((lvl_1.clone().unwrap_record().append.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x.clone()))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(g.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))
})
}
})
}
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(std::rc::Rc::new({ let _f = (_a).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(std::rc::Rc::new({ let _f = (_a).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } })) } }))), ..Default::default() }))
};
    crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Monoid::Dict_Monoid { mempty: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictMonoid = dictMonoid.clone();
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictMonoid.clone().unwrap_record().mempty.clone().unwrap()
}), Semigroup0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut semigroupFn = semigroupFn.clone();
    drop(_dollar___unused);
    semigroupFn.clone()
}) }))
}
}

pub fn Data_Monoid_monoidRecordCons(mut dictIsSymbol: crate::UnknownType, mut dictMonoid: crate::UnknownType, mut _dollar___unused: crate::UnknownType, mut dictMonoidRecord: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut mempty1 = /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictMonoid.clone().unwrap_record().mempty.clone().unwrap();
    {
    let mut Semigroup0 = (dictMonoid.unwrap_record().Semigroup0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut semigroupRecordCons1 = /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut lvl_6 = (dictMonoidRecord.clone().unwrap_record().SemigroupRecord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { appendRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    let mut Semigroup0 = Semigroup0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_6 = lvl_6.clone();
    drop(v);
    /* Typed Abs */{
    let mut Semigroup0 = Semigroup0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_6 = lvl_6.clone();
    std::rc::Rc::new(move |mut ra: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut Semigroup0 = Semigroup0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_6 = lvl_6.clone();
    /* Typed Abs */{
    let mut Semigroup0 = Semigroup0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_6 = lvl_6.clone();
    std::rc::Rc::new(move |mut rb: crate::UnknownType| -> crate::UnknownType {
    let mut Semigroup0 = Semigroup0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_6 = lvl_6.clone();
    let mut ra = ra.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut key = /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string();
    {
    let mut get = /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> <- std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> : App(Var(...)) */std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed String <- String : Local(...) */key.clone();
    crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Record_Unsafe_unsafeGet(eval_arg_0, eta_0.clone())
}))
}).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } });
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeSet(/* Typed String <- String : Local(...) */key, /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Semigroup0.clone().unwrap_record().append.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(get.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone()))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(get)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb.clone())), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(((lvl_6.clone().unwrap_record().appendRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb))
}
}
})
}
})
}
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } })) } }))), ..Default::default() }))
};
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { memptyRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut dictMonoidRecord = dictMonoidRecord.clone();
    let mut mempty1 = mempty1.clone();
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeSet(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string(), mempty1.clone(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonoidRecord.clone().unwrap_record().memptyRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() }))))
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), SemigroupRecord0: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut semigroupRecordCons1 = semigroupRecordCons1.clone();
    drop(_dollar___unused);
    semigroupRecordCons1.clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), ..Default::default() }))
}
}
}
}

pub fn Data_Monoid_power(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: i64) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dictMonoid: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(i64) -> crate::UnknownType>> {
    {
    let mut mempty1 = /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictMonoid.clone().unwrap_record().mempty.clone().unwrap();
    {
    let mut Semigroup0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonoid.unwrap_record().Semigroup0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed Abs */std::rc::Rc::new(move |mut x: crate::UnknownType| -> std::rc::Rc<dyn Fn(i64) -> crate::UnknownType> {
    let mut Semigroup0 = Semigroup0.clone();
    let mut mempty1 = mempty1.clone();
    /* Typed std::rc::Rc<dyn Fn(i64) -> crate::UnknownType> <- std::rc::Rc<dyn Fn(i64) -> crate::UnknownType> : LetRec(..., Typed(Local(...))) */{
    let mut go = crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }));
    let val_go = {
        let mut go = go.clone();
        crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut Semigroup0 = Semigroup0.clone();
    let mut go = go.clone();
    let mut mempty1 = mempty1.clone();
    std::rc::Rc::new(move |mut p: i64| -> crate::UnknownType {
    let mut Semigroup0 = Semigroup0.clone();
    let mut go = go.clone();
    let mut mempty1 = mempty1.clone();
    let mut x = x.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : PrimOp(...) */(/* Typed i64 <- i64 : Local(...) */p.clone() <= /* Typed i64 <- i64 : Lit */0) {
        mempty1.clone()
    } else if /* Typed bool <- bool : PrimOp(...) */(p.clone() == /* Typed i64 <- i64 : Lit */1) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x.clone()
    } else if /* Typed bool <- bool : PrimOp(...) */(Data_EuclideanRing_intMod(/* Typed i64 <- i64 : Local(...) */p.clone(), /* Typed i64 <- i64 : Lit */2) == /* Typed i64 <- i64 : Lit */0) {
        /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut x_prime = /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(go.clone()).unwrap_func()(crate::mk_int(/* Typed i64 <- i64 : PrimOp(...) */(p / /* Typed i64 <- i64 : Lit */2)));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Semigroup0.clone().unwrap_class::<crate::Purs_Data_Semigroup::Dict_Semigroup>().append.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x_prime.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x_prime)
}
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut x_prime = /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(go.clone()).unwrap_func()(crate::mk_int(/* Typed i64 <- i64 : PrimOp(...) */(p / /* Typed i64 <- i64 : Lit */2)));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Semigroup0.clone().unwrap_class::<crate::Purs_Data_Semigroup::Dict_Semigroup>().append.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x_prime.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Semigroup0.clone().unwrap_class::<crate::Purs_Data_Semigroup::Dict_Semigroup>().append.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x_prime)).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x.clone()))
}
    }
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f((_a).unwrap_int()) } }))
    };
    *(unsafe { perceus_ptr::PerceusPtr::force_mut(go.as_record_mut()) }) = crate::Record_a { call: Some((val_go).unwrap_func()), ..Default::default() };
    /* Typed std::rc::Rc<dyn Fn(i64) -> crate::UnknownType> <- crate::UnknownType : Local(...) */std::rc::Rc::new({ let _f = (go).unwrap_func(); move |mut _a: i64| -> crate::UnknownType { _f(crate::mk_int(_a)) } })
}
})
}
}
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Monoid_guard(mut dictMonoid: crate::UnknownType, mut v: bool, mut v1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut mempty1 = /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictMonoid.unwrap_record().mempty.clone().unwrap();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if v {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1
    } else {
        mempty1
    }
}
}





