#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;


// Code generated by purust for module Type_Proxy

#[derive(Clone)]
pub enum Proxy {
    Proxy
}


pub fn Type_Proxy_Proxy() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", ..Default::default() }))
}





