#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Effect_Console::*;
use Purs_Control_Applicative::*;
use Purs_Control_Bind::*;
use Purs_Control_Semigroupoid::*;
use Purs_Effect_Class::*;

// Code generated by purust for module Effect_Class_Console



pub fn Effect_Class_Console_warnShow(mut dictMonadEffect: crate::UnknownType, mut dictShow: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...))))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_warn(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_string()))
}

pub fn Effect_Class_Console_warn(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_warn((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_timeLog(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_timeLog((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_timeEnd(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_timeEnd((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_time(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_time((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_logShow(mut dictMonadEffect: crate::UnknownType, mut dictShow: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...))))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_string()))
}

pub fn Effect_Class_Console_log(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_infoShow(mut dictMonadEffect: crate::UnknownType, mut dictShow: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...))))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_info(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_string()))
}

pub fn Effect_Class_Console_info(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_info((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_groupEnd(mut dictMonadEffect: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Effect_Console_groupEnd())
}

pub fn Effect_Class_Console_groupCollapsed(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_groupCollapsed((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_group(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_group((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_grouped(mut dictMonadEffect: crate::UnknownType, mut name: String, mut inner: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Monad0 = (dictMonadEffect.clone().unwrap_record().Monad0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut Bind1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Monad0.clone().unwrap_record().Bind1.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut groupEnd1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.clone().unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Effect_Console_groupEnd());
    {
    let mut Applicative0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Monad0.unwrap_record().Applicative0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.clone().unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_group((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(name))).unwrap_string())))).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut Bind1 = Bind1.clone();
    let mut groupEnd1 = groupEnd1.clone();
    let mut inner = inner.clone();
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.clone().unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */inner.clone())).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut Applicative0 = Applicative0.clone();
    let mut Bind1 = Bind1.clone();
    let mut groupEnd1 = groupEnd1.clone();
    std::rc::Rc::new(move |mut result: crate::UnknownType| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut Bind1 = Bind1.clone();
    let mut groupEnd1 = groupEnd1.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.clone().unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(groupEnd1.clone())).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut Applicative0 = Applicative0.clone();
    std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut result = result.clone();
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Applicative0.clone().unwrap_class::<crate::Purs_Control_Applicative::Dict_Applicative>().pure.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */result.clone())
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))
}
}
}
}
}

pub fn Effect_Class_Console_errorShow(mut dictMonadEffect: crate::UnknownType, mut dictShow: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...))))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_error(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_string()))
}

pub fn Effect_Class_Console_error(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_error((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_debugShow(mut dictMonadEffect: crate::UnknownType, mut dictShow: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...))))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_debug(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)).unwrap_string()))
}

pub fn Effect_Class_Console_debug(mut dictMonadEffect: crate::UnknownType, mut x: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_debug((/* Typed crate::UnknownType <- String : Local(...) */crate::mk_string(&(x))).unwrap_string()))
}

pub fn Effect_Class_Console_clear(mut dictMonadEffect: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonadEffect.unwrap_record().liftEffect.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Effect_Console_clear())
}





