#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_Ring::*;

// Code generated by purust for module Data_Ring_Generic


#[derive(Clone)]
pub struct Dict_GenericRing {
    pub genericSub_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>
}

pub fn Data_Ring_Generic_genericSub_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericSub_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Ring_Generic_genericSub(mut dictGeneric: crate::UnknownType, mut dictGenericRing: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericRing.unwrap_record().genericSub_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)))
}

pub fn Data_Ring_Generic_genericRingProduct(mut dictGenericRing: crate::UnknownType, mut dictGenericRing1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ring_Generic::Dict_GenericRing { genericSub_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericRing = dictGenericRing.clone();
    let mut dictGenericRing1 = dictGenericRing1.clone();
    /* Typed Abs */{
    let mut dictGenericRing = dictGenericRing.clone();
    let mut dictGenericRing1 = dictGenericRing1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericRing = dictGenericRing.clone();
    let mut dictGenericRing1 = dictGenericRing1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericRing.clone().unwrap_record().genericSub_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericRing1.clone().unwrap_record().genericSub_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
})
}
}) }))
}

pub fn Data_Ring_Generic_genericRingNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ring_Generic::Dict_GenericRing { genericSub_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
})
}) }))
}

pub fn Data_Ring_Generic_genericRingConstructor(mut dictGenericRing: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ring_Generic::Dict_GenericRing { genericSub_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericRing = dictGenericRing.clone();
    /* Typed Abs */{
    let mut dictGenericRing = dictGenericRing.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericRing = dictGenericRing.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericRing.clone().unwrap_record().genericSub_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}) }))
}

pub fn Data_Ring_Generic_genericRingArgument(mut dictRing: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ring_Generic::Dict_GenericRing { genericSub_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictRing = dictRing.clone();
    /* Typed Abs */{
    let mut dictRing = dictRing.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictRing = dictRing.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictRing.clone().unwrap_record().sub.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}) }))
}





