#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;


// Code generated by purust for module Data_Field


#[derive(Clone)]
pub struct Dict_Field {
    pub EuclideanRing0: crate::UnknownType,
    pub DivisionRing1: crate::UnknownType
}

pub fn Data_Field_field(mut dictEuclideanRing: crate::UnknownType, mut dictDivisionRing: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Field::Dict_Field { EuclideanRing0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut dictEuclideanRing = dictEuclideanRing.clone();
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */dictEuclideanRing.clone()
}), DivisionRing1: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut dictDivisionRing = dictDivisionRing.clone();
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */dictDivisionRing.clone()
}) }))
}





