#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;


// Code generated by purust for module Effect_Unsafe





pub fn Effect_Unsafe_unsafePerformEffect(mut a0: crate::UnknownType) -> crate::UnknownType { UnknownType::new(Record_a { ..Default::default() }) }


