#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Show_Generic


#[derive(Clone)]
pub struct Dict_GenericShowArgs {
    pub genericShowArgs: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>
}

#[derive(Clone)]
pub struct Dict_GenericShow {
    pub genericShow_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> String>
}

pub fn Data_Show_Generic_genericShowArgsNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show_Generic::Dict_GenericShowArgs { genericShowArgs: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::mk_array(vec![])
}) }))
}

pub fn Data_Show_Generic_genericShowArgsArgument(mut dictShow: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show_Generic::Dict_GenericShowArgs { genericShowArgs: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictShow = dictShow.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::mk_array(vec![/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictShow.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v)).unwrap_string()])
}) }))
}

pub fn Data_Show_Generic_genericShowArgs(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericShowArgs.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_Show_Generic_genericShowArgsProduct(mut dictGenericShowArgs: crate::UnknownType, mut dictGenericShowArgs1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show_Generic::Dict_GenericShowArgs { genericShowArgs: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericShowArgs = dictGenericShowArgs.clone();
    let mut dictGenericShowArgs1 = dictGenericShowArgs1.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Semigroup_concatArray((dictGenericShowArgs.clone().unwrap_record().genericShowArgs.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), (dictGenericShowArgs1.clone().unwrap_record().genericShowArgs.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[1].clone()))
}) }))
}

pub fn Data_Show_Generic_genericShowConstructor(mut dictGenericShowArgs: crate::UnknownType, mut dictIsSymbol: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show_Generic::Dict_GenericShow { genericShow_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictGenericShowArgs = dictGenericShowArgs.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    /* Typed String <- String : Let(...) */{
    let mut ctor = /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string();
    /* Typed String <- String : Let(...) */{
    let mut v1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGenericShowArgs.clone().unwrap_record().genericShowArgs.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v);
    if (((v1.clone()).unwrap_array().len() as i64) == 0) {
        /* Typed String <- String : Local(...) */ctor
    } else {
        /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from(r#"("#), Data_Show_Generic_intercalate(/* Typed String <- String : Lit */String::from(r#" "#), /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Semigroup_concatArray(crate::mk_array(vec![/* Typed String <- String : Local(...) */ctor]), v1))), String::from(r#")"#))
    }
}
}
}) }))
}

pub fn Data_Show_Generic_genericShow_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> String {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> String> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericShow_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> String { (_f(_a)).unwrap_string() } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_Show_Generic_genericShowNoConstructors() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show_Generic::Dict_GenericShow { genericShow_prime: /* Typed Abs */std::rc::Rc::new(move |mut a: crate::UnknownType| -> String {
    /* Typed String <- crate::UnknownType : App(Accessor(Var(...))) */((Data_Show_Generic_genericShowNoConstructors().clone().unwrap_class::<crate::Purs_Data_Show_Generic::Dict_GenericShow>().genericShow_prime.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_string()
}) }))
}

pub fn Data_Show_Generic_genericShowSum(mut dictGenericShow: crate::UnknownType, mut dictGenericShow1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show_Generic::Dict_GenericShow { genericShow_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictGenericShow = dictGenericShow.clone();
    let mut dictGenericShow1 = dictGenericShow1.clone();
    /* Typed String <- String : Branch(...) */if (v.clone().unwrap_record().tag == "Inl") {
        /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericShow.clone().unwrap_record().genericShow_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_string()
    } else if (v.clone().unwrap_record().tag == "Inr") {
        /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericShow1.clone().unwrap_record().genericShow_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_string()
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}) }))
}

pub fn Data_Show_Generic_genericShow(mut dictGeneric: crate::UnknownType, mut dictGenericShow: crate::UnknownType, mut x: crate::UnknownType) -> String {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))
/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericShow.unwrap_record().genericShow_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_string()
}



pub fn Data_Show_Generic_intercalate(mut a0: String, mut a1: crate::UnknownType) -> String { String::new() }


