[package]
name = "Purs_Data_Bounded"
version = "0.1.0"
edition = "2021"

[dependencies]
purust_core = { path = "../purust_core" }
perceus_ptr = { path = "/Users/0x1/Documents/htdocs/purust/purust/tests/runtime/perceus_ptr" }
fancy-regex = "0.13"
Purs_Data_Unit = { path = "../Purs_Data_Unit" }
Purs_Record_Unsafe = { path = "../Purs_Record_Unsafe" }
Purs_Data_Ord = { path = "../Purs_Data_Ord" }
Purs_Data_Ordering = { path = "../Purs_Data_Ordering" }
Purs_Data_Symbol = { path = "../Purs_Data_Symbol" }
Purs_Type_Proxy = { path = "../Purs_Type_Proxy" }