#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Show::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Symbol::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Generic_Rep

#[derive(Clone)]
pub enum NoArguments {
    NoArguments
}

#[derive(Clone)]
pub enum Product {
    Product(crate::UnknownType, crate::UnknownType)
}

#[derive(Clone)]
pub enum Sum {
    Inl(crate::UnknownType),
    Inr(crate::UnknownType)
}

#[derive(Clone)]
pub struct Dict_Generic {
    pub to: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>,
    pub from: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>
}

pub fn Data_Generic_Rep_Inl() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Inl", ..Default::default() }))
}

pub fn Data_Generic_Rep_Inr() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Inr", ..Default::default() }))
}

pub fn Data_Generic_Rep_Product() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", ..Default::default() }))
}

pub fn Data_Generic_Rep_NoArguments() -> crate::UnknownType {
    // AST: CtorDef
crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", ..Default::default() }))
}

pub fn Data_Generic_Rep_Constructor(mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Abs(..., Local(...))
x
}

pub fn Data_Generic_Rep_Argument(mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Abs(..., Local(...))
x
}

pub fn Data_Generic_Rep_to(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().to.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_Generic_Rep_showSum(mut dictShow: crate::UnknownType, mut dictShow1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictShow = dictShow.clone();
    let mut dictShow1 = dictShow1.clone();
    /* Typed String <- String : Branch(...) */if (v.clone().unwrap_record().tag == "Inl") {
        /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from(r#"(Inl "#), ((dictShow.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_string()), String::from(r#")"#))
    } else if (v.clone().unwrap_record().tag == "Inr") {
        /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from(r#"(Inr "#), ((dictShow1.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_string()), String::from(r#")"#))
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}) }))
}

pub fn Data_Generic_Rep_showProduct(mut dictShow: crate::UnknownType, mut dictShow1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictShow = dictShow.clone();
    let mut dictShow1 = dictShow1.clone();
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", String::from(r#"(Product "#), ((dictShow.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_string()), String::from(r#" "#)), ((dictShow1.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_string()), String::from(r#")"#))
}) }))
}

pub fn Data_Generic_Rep_showNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    drop(v);
    /* Typed String <- String : Lit */String::from(r#"NoArguments"#)
}) }))
}

pub fn Data_Generic_Rep_showConstructor(mut dictIsSymbol: crate::UnknownType, mut dictShow: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut dictShow = dictShow.clone();
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", String::from(r#"(Constructor @"#), Data_Show_showStringImpl(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string())), String::from(r#" "#)), ((dictShow.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v)).unwrap_string()), String::from(r#")"#))
}) }))
}

pub fn Data_Generic_Rep_showArgument(mut dictShow: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Show::Dict_Show { show: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> String {
    let mut dictShow = dictShow.clone();
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from(r#"(Argument "#), ((dictShow.clone().unwrap_record().show.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v)).unwrap_string()), String::from(r#")"#))
}) }))
}

pub fn Data_Generic_Rep_repOf(mut dictGeneric: crate::UnknownType, mut v: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(CtorSaturated(...)))))))
/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() }))
}

pub fn Data_Generic_Rep_from(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().from.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}





