#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Boolean::*;
use Purs_Data_Ord::*;
use Purs_Data_Ring::*;

// Code generated by purust for module Data_Function



pub fn Data_Function_on(mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>, mut g: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */((f)(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(g.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)))(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(g)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y))
}

pub fn Data_Function_flip(mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>, mut b: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Local(...)))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */((f)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a))(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */b)
}

pub fn Data_Function_const(mut a: crate::UnknownType, mut v: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Local(...)))))))
/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a
}

pub fn Data_Function_applyN(mut a0: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>, mut a1: i64, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(LetRec(..., Typed(Local(...)))))))
(((/* Typed Abs */std::rc::Rc::new(move |mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(i64) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    /* Typed std::rc::Rc<dyn Fn(i64) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> <- std::rc::Rc<dyn Fn(i64) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> : LetRec(..., Typed(Local(...))) */{
    let mut go = crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }));
    let val_go = {
        let mut go = go.clone();
        crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut go = go.clone();
    std::rc::Rc::new(move |mut n: i64| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut f = f.clone();
    let mut go = go.clone();
    /* Typed Abs */{
    let mut f = f.clone();
    let mut go = go.clone();
    std::rc::Rc::new(move |mut acc: crate::UnknownType| -> crate::UnknownType {
    let mut f = f.clone();
    let mut go = go.clone();
    let mut n = n.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : PrimOp(...) */(/* Typed i64 <- i64 : Local(...) */n.clone() <= /* Typed i64 <- i64 : Lit */0) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */acc
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */((go.clone()).unwrap_func()(crate::mk_int(/* Typed i64 <- i64 : PrimOp(...) */(n.clone() - /* Typed i64 <- i64 : Lit */1)))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */acc))
    }
})
}
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f((_a).unwrap_int())).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } }))
    };
    *(unsafe { perceus_ptr::PerceusPtr::force_mut(go.as_record_mut()) }) = crate::Record_a { call: Some((val_go).unwrap_func()), ..Default::default() };
    /* Typed std::rc::Rc<dyn Fn(i64) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> <- crate::UnknownType : Local(...) */std::rc::Rc::new({ let _f = (go).unwrap_func(); move |mut _a: i64| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(crate::mk_int(_a))).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Function_applyFlipped(mut x: crate::UnknownType, mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Local(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)
}

pub fn Data_Function_apply(mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Local(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)
}





