#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Eq::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;

// Code generated by purust for module Data_Eq_Generic


#[derive(Clone)]
pub struct Dict_GenericEq {
    pub genericEq_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>>
}

pub fn Data_Eq_Generic_genericEqNoConstructors() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq_Generic::Dict_GenericEq { genericEq_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    drop(v1);
    /* Typed bool <- bool : Lit */true
})
}) }))
}

pub fn Data_Eq_Generic_genericEqNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq_Generic::Dict_GenericEq { genericEq_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    drop(v1);
    /* Typed bool <- bool : Lit */true
})
}) }))
}

pub fn Data_Eq_Generic_genericEqArgument(mut dictEq: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq_Generic::Dict_GenericEq { genericEq_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    let mut dictEq = dictEq.clone();
    /* Typed Abs */{
    let mut dictEq = dictEq.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    let mut dictEq = dictEq.clone();
    let mut v = v.clone();
    /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */(((dictEq.clone().unwrap_record().eq.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)).unwrap_bool()
})
}
}) }))
}

pub fn Data_Eq_Generic_genericEq_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Eq_Generic_genericEqConstructor(mut dictGenericEq: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq_Generic::Dict_GenericEq { genericEq_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    let mut dictGenericEq = dictGenericEq.clone();
    /* Typed Abs */{
    let mut dictGenericEq = dictGenericEq.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    let mut dictGenericEq = dictGenericEq.clone();
    let mut v = v.clone();
    /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */(((dictGenericEq.clone().unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)).unwrap_bool()
})
}
}) }))
}

pub fn Data_Eq_Generic_genericEqProduct(mut dictGenericEq: crate::UnknownType, mut dictGenericEq1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq_Generic::Dict_GenericEq { genericEq_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    let mut dictGenericEq = dictGenericEq.clone();
    let mut dictGenericEq1 = dictGenericEq1.clone();
    /* Typed Abs */{
    let mut dictGenericEq = dictGenericEq.clone();
    let mut dictGenericEq1 = dictGenericEq1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    let mut dictGenericEq = dictGenericEq.clone();
    let mut dictGenericEq1 = dictGenericEq1.clone();
    let mut v = v.clone();
    /* Typed bool <- bool : PrimOp(...) */((((dictGenericEq.clone().unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_bool() && /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */(((dictGenericEq1.clone().unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_bool())
})
}
}) }))
}

pub fn Data_Eq_Generic_genericEqSum(mut dictGenericEq: crate::UnknownType, mut dictGenericEq1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq_Generic::Dict_GenericEq { genericEq_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    let mut dictGenericEq = dictGenericEq.clone();
    let mut dictGenericEq1 = dictGenericEq1.clone();
    /* Typed Abs */{
    let mut dictGenericEq = dictGenericEq.clone();
    let mut dictGenericEq1 = dictGenericEq1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> bool {
    let mut dictGenericEq = dictGenericEq.clone();
    let mut dictGenericEq1 = dictGenericEq1.clone();
    let mut v = v.clone();
    /* Typed bool <- bool : Branch(...) */if (v.clone().unwrap_record().tag == "Inl") {
        ((v1.clone().unwrap_record().tag == "Inl") && /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */(((dictGenericEq.clone().unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_bool())
    } else {
        ((v.clone().unwrap_record().tag == "Inr") && ((v1.clone().unwrap_record().tag == "Inr") && /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */(((dictGenericEq1.clone().unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_bool()))
    }
})
}
}) }))
}

pub fn Data_Eq_Generic_genericEq(mut dictGeneric: crate::UnknownType, mut dictGenericEq: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */(((dictGenericEq.unwrap_record().genericEq_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y))).unwrap_bool()
}





