#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Unit::*;
use Purs_Record_Unsafe::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Symbol::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Bounded


#[derive(Clone)]
pub struct Dict_BoundedRecord {
    pub OrdRecord0: crate::UnknownType,
    pub topRecord: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>,
    pub bottomRecord: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>
}

#[derive(Clone)]
pub struct Dict_Bounded {
    pub Ord0: crate::UnknownType,
    pub top: crate::UnknownType,
    pub bottom: crate::UnknownType
}

pub fn Data_Bounded_topRecord(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().topRecord.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Bounded_top(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().top.clone().unwrap()
}

pub fn Data_Bounded_boundedUnit() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Unit_unit(), bottom: /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Unit_unit(), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordUnit().clone()
}) }))
}

pub fn Data_Bounded_boundedRecordNil() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { topRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }))
})
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } }))), bottomRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }))
})
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } }))), OrdRecord0: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordRecordNil().clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), ..Default::default() }))
}

pub fn Data_Bounded_boundedProxy() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { bottom: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })), top: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordProxy().clone()
}) }))
}

pub fn Data_Bounded_boundedOrdering() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "GT", vals: None, ..Default::default() })), bottom: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "LT", vals: None, ..Default::default() })), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordOrdering().clone()
}) }))
}

pub fn Data_Bounded_boundedNumber() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed f64 <- f64 : Var(...) */Data_Bounded_topNumber(), bottom: /* Typed f64 <- f64 : Var(...) */Data_Bounded_bottomNumber(), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordNumber().clone()
}) }))
}

pub fn Data_Bounded_boundedInt() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed i64 <- i64 : Var(...) */Data_Bounded_topInt(), bottom: /* Typed i64 <- i64 : Var(...) */Data_Bounded_bottomInt(), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordInt().clone()
}) }))
}

pub fn Data_Bounded_boundedChar() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed char <- char : Var(...) */Data_Bounded_topChar(), bottom: /* Typed char <- char : Var(...) */Data_Bounded_bottomChar(), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordChar().clone()
}) }))
}

pub fn Data_Bounded_boundedBoolean() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed bool <- bool : Lit */true, bottom: /* Typed bool <- bool : Lit */false, Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Ord_ordBoolean().clone()
}) }))
}

pub fn Data_Bounded_bottomRecord(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().bottomRecord.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Bounded_boundedRecord(mut _dollar___unused: crate::UnknownType, mut dictBoundedRecord: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut ordRecord1 = /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut lvl_2 = (dictBoundedRecord.clone().unwrap_record().OrdRecord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut eqRec1 = crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Eq::Dict_Eq { eq: /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> <- crate::UnknownType : App(Accessor(App(Accessor(Local(...))))) */std::rc::Rc::new({ let _f = (((lvl_2.clone().unwrap_record().EqRecord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))).unwrap_record().eqRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> bool { (_f(_a)).unwrap_bool() } }) } }) }));
    crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Ord::Dict_Ord { compare: /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> <- crate::UnknownType : App(Accessor(Local(...))) */std::rc::Rc::new({ let _f = ((lvl_2.unwrap_record().compareRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } }), Eq0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut eqRec1 = eqRec1.clone();
    drop(_dollar___unused);
    eqRec1.clone()
}) }))
}
};
    crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Bounded::Dict_Bounded { top: /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictBoundedRecord.unwrap_record().topRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() }))), bottom: /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictBoundedRecord.unwrap_record().bottomRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() }))), Ord0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut ordRecord1 = ordRecord1.clone();
    drop(_dollar___unused);
    ordRecord1.clone()
}) }))
}
}

pub fn Data_Bounded_bottom(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().bottom.clone().unwrap()
}

pub fn Data_Bounded_boundedRecordCons(mut dictIsSymbol: crate::UnknownType, mut dictBounded: crate::UnknownType, mut _dollar___unused: crate::UnknownType, mut _dollar___unused_1: crate::UnknownType, mut dictBoundedRecord: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut top1 = /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictBounded.clone().unwrap_record().top.clone().unwrap();
    {
    let mut bottom1 = /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictBounded.clone().unwrap_record().bottom.clone().unwrap();
    {
    let mut Ord0 = (dictBounded.unwrap_record().Ord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut ordRecordCons = /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut lvl_8 = (dictBoundedRecord.clone().unwrap_record().OrdRecord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut eqRowCons2 = /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut lvl_9 = (lvl_8.clone().unwrap_record().EqRecord0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut lvl_10 = (Ord0.clone().unwrap_record().Eq0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { eqRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool>> {
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_10 = lvl_10.clone();
    let mut lvl_9 = lvl_9.clone();
    drop(v);
    /* Typed Abs */{
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_10 = lvl_10.clone();
    let mut lvl_9 = lvl_9.clone();
    std::rc::Rc::new(move |mut ra: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> bool> {
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_10 = lvl_10.clone();
    let mut lvl_9 = lvl_9.clone();
    /* Typed Abs */{
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_10 = lvl_10.clone();
    let mut lvl_9 = lvl_9.clone();
    std::rc::Rc::new(move |mut rb: crate::UnknownType| -> bool {
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_10 = lvl_10.clone();
    let mut lvl_9 = lvl_9.clone();
    let mut ra = ra.clone();
    /* Typed bool <- bool : Let(...) */{
    let mut get = /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> <- std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> : App(Var(...)) */std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string();
    crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Record_Unsafe_unsafeGet(eval_arg_0, eta_0.clone())
}))
}).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } });
    /* Typed bool <- bool : PrimOp(...) */((((lvl_10.clone().unwrap_record().eq.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(get.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone()))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(get)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb.clone()))).unwrap_bool() && /* Typed bool <- crate::UnknownType : App(Accessor(Local(...))) */((((lvl_9.clone().unwrap_record().eqRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb)).unwrap_bool())
}
})
}
})
}
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(_a)) } })) } })) } }))), ..Default::default() }))
}
};
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { compareRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    let mut Ord0 = Ord0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_8 = lvl_8.clone();
    drop(v);
    /* Typed Abs */{
    let mut Ord0 = Ord0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_8 = lvl_8.clone();
    std::rc::Rc::new(move |mut ra: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut Ord0 = Ord0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_8 = lvl_8.clone();
    /* Typed Abs */{
    let mut Ord0 = Ord0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_8 = lvl_8.clone();
    std::rc::Rc::new(move |mut rb: crate::UnknownType| -> crate::UnknownType {
    let mut Ord0 = Ord0.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut lvl_8 = lvl_8.clone();
    let mut ra = ra.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut key = /* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string();
    {
    let mut left = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Ord0.clone().unwrap_record().compare.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeGet(/* Typed String <- String : Local(...) */key.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone()))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeGet(/* Typed String <- String : Local(...) */key, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb.clone()));
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : PrimOp(...) */!((left.clone().unwrap_record().tag == "EQ") /* aTy: bool, a is PrimOp(...), fn ty is not app */) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */left
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(((lvl_8.clone().unwrap_record().compareRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ra.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rb)
    }
}
}
})
}
})
}
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } })) } }))), EqRecord0: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut eqRowCons2 = eqRowCons2.clone();
    drop(_dollar___unused);
    eqRowCons2.clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), ..Default::default() }))
}
};
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { topRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut top1 = top1.clone();
    drop(v);
    /* Typed Abs */{
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut top1 = top1.clone();
    std::rc::Rc::new(move |mut rowProxy: crate::UnknownType| -> crate::UnknownType {
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    let mut top1 = top1.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeSet(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string(), top1.clone(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictBoundedRecord.clone().unwrap_record().topRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rowProxy))
})
}
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } }))), bottomRecord: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut bottom1 = bottom1.clone();
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    drop(v);
    /* Typed Abs */{
    let mut bottom1 = bottom1.clone();
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    std::rc::Rc::new(move |mut rowProxy: crate::UnknownType| -> crate::UnknownType {
    let mut bottom1 = bottom1.clone();
    let mut dictBoundedRecord = dictBoundedRecord.clone();
    let mut dictIsSymbol = dictIsSymbol.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeSet(/* Typed String <- crate::UnknownType : App(Accessor(Local(...))) */((dictIsSymbol.clone().unwrap_record().reflectSymbol.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_string(), bottom1.clone(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictBoundedRecord.clone().unwrap_record().bottomRecord.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */rowProxy))
})
}
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { crate::Value::Func(std::rc::Rc::new({ let _f = (_f(_a)).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } }))), OrdRecord0: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    let mut ordRecordCons = ordRecordCons.clone();
    drop(_dollar___unused);
    ordRecordCons.clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), ..Default::default() }))
}
}
}
}
}



pub fn Data_Bounded_bottomChar() -> char {
    '\u{0}'
}

pub fn Data_Bounded_topChar() -> char {
    '\u{FFFF}'
}

pub fn Data_Bounded_bottomInt() -> i64 {
    -2147483648
}

pub fn Data_Bounded_topInt() -> i64 {
    2147483647
}

pub fn Data_Bounded_bottomNumber() -> f64 {
    std::f64::NEG_INFINITY
}

pub fn Data_Bounded_topNumber() -> f64 {
    std::f64::INFINITY
}




