#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;


// Code generated by purust for module Data_Boolean



pub fn Data_Boolean_otherwise() -> bool {
    // AST: Typed(Typed(Lit))
/* Typed bool <- bool : Lit */true
}





