#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Unit::*;
use Purs_Control_Applicative::*;
use Purs_Control_Bind::*;

// Code generated by purust for module Control_Monad


#[derive(Clone)]
pub struct Dict_Monad {
    pub Applicative0: crate::UnknownType,
    pub Bind1: crate::UnknownType
}

pub fn Control_Monad_whenM(mut dictMonad: crate::UnknownType, mut mb: crate::UnknownType, mut m: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Bind1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.clone().unwrap_record().Bind1.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut Applicative0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.unwrap_record().Applicative0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */mb)).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut b: bool| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut m = m.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : Local(...) */b {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */m.clone()
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Applicative0.clone().unwrap_class::<crate::Purs_Control_Applicative::Dict_Applicative>().pure.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Unit_unit().clone())
    }
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f((_a).unwrap_bool()) } })))
}
}
}

pub fn Control_Monad_unlessM(mut dictMonad: crate::UnknownType, mut mb: crate::UnknownType, mut m: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Bind1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.clone().unwrap_record().Bind1.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut Applicative0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.unwrap_record().Applicative0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */mb)).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut b: bool| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut m = m.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if !(/* Typed bool <- bool : Local(...) */b.clone() /* aTy: bool, a is Typed(Local(...)), fn ty is not app */) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */m.clone()
    } else if /* Typed bool <- bool : Local(...) */b {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Applicative0.clone().unwrap_class::<crate::Purs_Control_Applicative::Dict_Applicative>().pure.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Unit_unit().clone())
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f((_a).unwrap_bool()) } })))
}
}
}

pub fn Control_Monad_monadProxy() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Monad::Dict_Monad { Applicative0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Applicative_applicativeProxy().clone()
}), Bind1: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Bind_bindProxy().clone()
}) }))
}

pub fn Control_Monad_monadFn() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Monad::Dict_Monad { Applicative0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Applicative_applicativeFn().clone()
}), Bind1: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Bind_bindFn().clone()
}) }))
}

pub fn Control_Monad_monadArray() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Control_Monad::Dict_Monad { Applicative0: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Applicative_applicativeArray().clone()
}), Bind1: /* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Bind_bindArray().clone()
}) }))
}

pub fn Control_Monad_liftM1(mut dictMonad: crate::UnknownType, mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Bind1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.clone().unwrap_record().Bind1.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut Applicative0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.unwrap_record().Applicative0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a)).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut a_prime: crate::UnknownType| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut f = f.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Applicative0.clone().unwrap_class::<crate::Purs_Control_Applicative::Dict_Applicative>().pure.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a_prime))
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))
}
}
}

pub fn Control_Monad_ap(mut dictMonad: crate::UnknownType, mut f: crate::UnknownType, mut a: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut Bind1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.clone().unwrap_record().Bind1.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut Applicative0 = /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictMonad.unwrap_record().Applicative0.clone().unwrap()).unwrap_func()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.clone().unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */f)).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut f_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut Bind1 = Bind1.clone();
    let mut a = a.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((Bind1.clone().unwrap_class::<crate::Purs_Control_Bind::Dict_Bind>().bind.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a.clone())).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */{
    let mut Applicative0 = Applicative0.clone();
    std::rc::Rc::new(move |mut a_prime: crate::UnknownType| -> crate::UnknownType {
    let mut Applicative0 = Applicative0.clone();
    let mut f_prime = f_prime.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(Applicative0.clone().unwrap_class::<crate::Purs_Control_Applicative::Dict_Applicative>().pure.clone()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f_prime.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */a_prime))
})
}).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(std::rc::Rc::new({ let _f = (_a).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } })))
}
}
}





