#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Unit::*;
use Purs_Data_Function::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Functor


#[derive(Clone)]
pub struct Dict_Functor {
    pub map: std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>
}

pub fn Data_Functor_map(mut a0: crate::UnknownType, mut a1: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().map.clone().unwrap()).unwrap_func(); move |mut _a: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(crate::Value::Func(std::rc::Rc::new({ let _f = (_a).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Functor_mapFlipped(mut dictFunctor: crate::UnknownType, mut fa: crate::UnknownType, mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictFunctor.unwrap_record().map.clone().unwrap()).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> <- std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> : Local(...) */f).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */fa)
}

pub fn Data_Functor_void(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))
((/* Typed Abs */std::rc::Rc::new(move |mut dictFunctor: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> <- crate::UnknownType : App(Accessor(Local(...))) */std::rc::Rc::new({ let _f = ((dictFunctor.unwrap_record().map.clone().unwrap()).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Data_Unit_unit().clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_Functor_voidLeft(mut dictFunctor: crate::UnknownType, mut f: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictFunctor.unwrap_record().map.clone().unwrap()).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut x = x.clone();
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x.clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */f)
}

pub fn Data_Functor_voidRight(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dictFunctor: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    /* Typed Abs */std::rc::Rc::new(move |mut x: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictFunctor = dictFunctor.clone();
    /* Typed std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> <- crate::UnknownType : App(Accessor(Local(...))) */std::rc::Rc::new({ let _f = ((dictFunctor.clone().unwrap_record().map.clone().unwrap()).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut x = x.clone();
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x.clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
})
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Functor_functorProxy() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Functor::Dict_Functor { map: /* Typed Abs */std::rc::Rc::new(move |mut v: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Proxy", vals: None, ..Default::default() }))
})
}) }))
}

pub fn Data_Functor_functorFn() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Functor::Dict_Functor { map: /* Typed std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>> <- crate::UnknownType : Accessor(Var(...)) */std::rc::Rc::new({ let _f = (Control_Semigroupoid_semigroupoidFn().unwrap_record().compose.clone().unwrap()).unwrap_func(); move |mut _a: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> { std::rc::Rc::new({ let _f = (_f(crate::Value::Func(std::rc::Rc::new({ let _f = (_a).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func(); move |mut _a: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(crate::Value::Func(std::rc::Rc::new({ let _f = (_a).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } }) } }) }))
}

pub fn Data_Functor_functorArray() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Functor::Dict_Functor { map: /* Typed std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> <- std::rc::Rc<dyn Fn(std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> : Var(...) */std::rc::Rc::new({ let _f = (crate::Value::Func(std::rc::Rc::new(move |mut eta_0: UnknownType| -> UnknownType {  crate::Value::Func(std::rc::Rc::new(move |mut eta_1: UnknownType| -> UnknownType { let mut eta_0 = eta_0.clone(); Data_Functor_arrayMap(std::rc::Rc::new({ let _f = (eta_0.clone()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }), eta_1.clone()) })) }))).unwrap_func(); move |mut _a: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(crate::Value::Func(std::rc::Rc::new({ let _f = (_a).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })))).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } }) }))
}

pub fn Data_Functor_flap(mut dictFunctor: crate::UnknownType, mut ff: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(App(Accessor(Local(...)))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictFunctor.unwrap_record().map.clone().unwrap()).unwrap_func()(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>| -> crate::UnknownType {
    let mut x = x.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(f)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x.clone())
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(std::rc::Rc::new({ let _f = (_a).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })) } })))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */ff)
}



pub fn Data_Functor_arrayMap(mut f: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>, mut arr: crate::UnknownType) -> crate::UnknownType {
    let mut result = Vec::new();
    let a = arr.unwrap_array();
    for i in 0..a.len() {
        result.push(f(a[i].clone()));
    }
    crate::mk_array(result)
}




