#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;

// Code generated by purust for module Data_HeytingAlgebra_Generic


#[derive(Clone)]
pub struct Dict_GenericHeytingAlgebra {
    pub genericFF_prime: crate::UnknownType,
    pub genericTT_prime: crate::UnknownType,
    pub genericImplies_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>,
    pub genericConj_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>,
    pub genericDisj_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>,
    pub genericNot_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>
}

pub fn Data_HeytingAlgebra_Generic_genericTT_prime(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().genericTT_prime.clone().unwrap()
}

pub fn Data_HeytingAlgebra_Generic_genericTT(mut dictGeneric: crate::UnknownType, mut dictGenericHeytingAlgebra: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericHeytingAlgebra.unwrap_record().genericTT_prime.clone().unwrap())
}

pub fn Data_HeytingAlgebra_Generic_genericNot_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericNot_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } })
}))(a0.clone()))(a1.clone())
}

pub fn Data_HeytingAlgebra_Generic_genericNot(mut dictGeneric: crate::UnknownType, mut dictGenericHeytingAlgebra: crate::UnknownType, mut x: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGenericHeytingAlgebra.unwrap_record().genericNot_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x)))
}

pub fn Data_HeytingAlgebra_Generic_genericImplies_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericImplies_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_HeytingAlgebra_Generic_genericImplies(mut dictGeneric: crate::UnknownType, mut dictGenericHeytingAlgebra: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.unwrap_record().genericImplies_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)))
}

pub fn Data_HeytingAlgebra_Generic_genericHeytingAlgebraNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_HeytingAlgebra_Generic::Dict_GenericHeytingAlgebra { genericFF_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() })), genericTT_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() })), genericImplies_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
})
}), genericConj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
})
}), genericDisj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
})
}), genericNot_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    drop(v);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
}) }))
}

pub fn Data_HeytingAlgebra_Generic_genericHeytingAlgebraArgument(mut dictHeytingAlgebra: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_HeytingAlgebra_Generic::Dict_GenericHeytingAlgebra { genericFF_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictHeytingAlgebra.unwrap_record().ff.clone().unwrap(), genericTT_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictHeytingAlgebra.unwrap_record().tt.clone().unwrap(), genericImplies_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    /* Typed Abs */{
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictHeytingAlgebra.clone().unwrap_record().implies.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericConj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    /* Typed Abs */{
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictHeytingAlgebra.clone().unwrap_record().conj.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericDisj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    /* Typed Abs */{
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictHeytingAlgebra.clone().unwrap_record().disj.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericNot_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictHeytingAlgebra = dictHeytingAlgebra.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictHeytingAlgebra.clone().unwrap_record().not.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v)
}) }))
}

pub fn Data_HeytingAlgebra_Generic_genericFF_prime(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().genericFF_prime.clone().unwrap()
}

pub fn Data_HeytingAlgebra_Generic_genericFF(mut dictGeneric: crate::UnknownType, mut dictGenericHeytingAlgebra: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericHeytingAlgebra.unwrap_record().genericFF_prime.clone().unwrap())
}

pub fn Data_HeytingAlgebra_Generic_genericDisj_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericDisj_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_HeytingAlgebra_Generic_genericDisj(mut dictGeneric: crate::UnknownType, mut dictGenericHeytingAlgebra: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.unwrap_record().genericDisj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)))
}

pub fn Data_HeytingAlgebra_Generic_genericConj_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericConj_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_HeytingAlgebra_Generic_genericHeytingAlgebraConstructor(mut dictGenericHeytingAlgebra: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_HeytingAlgebra_Generic::Dict_GenericHeytingAlgebra { genericFF_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericHeytingAlgebra.unwrap_record().genericFF_prime.clone().unwrap(), genericTT_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericHeytingAlgebra.unwrap_record().genericTT_prime.clone().unwrap(), genericImplies_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    /* Typed Abs */{
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.clone().unwrap_record().genericImplies_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericConj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    /* Typed Abs */{
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.clone().unwrap_record().genericConj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericDisj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    /* Typed Abs */{
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.clone().unwrap_record().genericDisj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericNot_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGenericHeytingAlgebra.clone().unwrap_record().genericNot_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v)
}) }))
}

pub fn Data_HeytingAlgebra_Generic_genericHeytingAlgebraProduct(mut dictGenericHeytingAlgebra: crate::UnknownType, mut dictGenericHeytingAlgebra1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_HeytingAlgebra_Generic::Dict_GenericHeytingAlgebra { genericFF_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![dictGenericHeytingAlgebra.unwrap_record().genericFF_prime.clone().unwrap(), dictGenericHeytingAlgebra1.unwrap_record().genericFF_prime.clone().unwrap()])), ..Default::default() })), genericTT_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![dictGenericHeytingAlgebra.unwrap_record().genericTT_prime.clone().unwrap(), dictGenericHeytingAlgebra1.unwrap_record().genericTT_prime.clone().unwrap()])), ..Default::default() })), genericImplies_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    /* Typed Abs */{
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.clone().unwrap_record().genericImplies_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra1.clone().unwrap_record().genericImplies_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
})
}
}), genericConj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    /* Typed Abs */{
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.clone().unwrap_record().genericConj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra1.clone().unwrap_record().genericConj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
})
}
}), genericDisj_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    /* Typed Abs */{
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.clone().unwrap_record().genericDisj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra1.clone().unwrap_record().genericDisj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
})
}
}), genericNot_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericHeytingAlgebra = dictGenericHeytingAlgebra.clone();
    let mut dictGenericHeytingAlgebra1 = dictGenericHeytingAlgebra1.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGenericHeytingAlgebra.clone().unwrap_record().genericNot_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGenericHeytingAlgebra1.clone().unwrap_record().genericNot_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
}) }))
}

pub fn Data_HeytingAlgebra_Generic_genericConj(mut dictGeneric: crate::UnknownType, mut dictGenericHeytingAlgebra: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericHeytingAlgebra.unwrap_record().genericConj_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)))
}





