#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Semigroupoid::*;

// Code generated by purust for module Control_Category


#[derive(Clone)]
pub struct Dict_Category {
    pub Semigroupoid0: crate::UnknownType,
    pub identity: crate::UnknownType
}

pub fn Control_Category_identity(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().identity.clone().unwrap()
}

pub fn Control_Category_categoryFn() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { identity: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut x: crate::UnknownType| -> crate::UnknownType {
    /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), Semigroupoid0: Some(crate::Value::Func(std::rc::Rc::new({ let _f = (/* Typed Abs */std::rc::Rc::new(move |mut _dollar___unused: crate::UnknownType| -> crate::UnknownType {
    drop(_dollar___unused);
    /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Control_Semigroupoid_semigroupoidFn().clone()
})).clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }))), ..Default::default() }))
}





