#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_Semiring::*;

// Code generated by purust for module Data_Semiring_Generic


#[derive(Clone)]
pub struct Dict_GenericSemiring {
    pub genericAdd_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>,
    pub genericZero_prime: crate::UnknownType,
    pub genericMul_prime: std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>>,
    pub genericOne_prime: crate::UnknownType
}

pub fn Data_Semiring_Generic_genericZero_prime(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().genericZero_prime.clone().unwrap()
}

pub fn Data_Semiring_Generic_genericZero(mut dictGeneric: crate::UnknownType, mut dictGenericSemiring: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericSemiring.unwrap_record().genericZero_prime.clone().unwrap())
}

pub fn Data_Semiring_Generic_genericSemiringNoArguments() -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Lit)))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semiring_Generic::Dict_GenericSemiring { genericAdd_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
})
}), genericZero_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() })), genericMul_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    drop(v);
    /* Typed Abs */std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    drop(v1);
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() }))
})
}), genericOne_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "NoArguments", vals: None, ..Default::default() })) }))
}

pub fn Data_Semiring_Generic_genericSemiringArgument(mut dictSemiring: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semiring_Generic::Dict_GenericSemiring { genericAdd_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictSemiring = dictSemiring.clone();
    /* Typed Abs */{
    let mut dictSemiring = dictSemiring.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictSemiring = dictSemiring.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictSemiring.clone().unwrap_record().add.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericZero_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictSemiring.unwrap_record().zero.clone().unwrap(), genericMul_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictSemiring = dictSemiring.clone();
    /* Typed Abs */{
    let mut dictSemiring = dictSemiring.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictSemiring = dictSemiring.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictSemiring.clone().unwrap_record().mul.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericOne_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictSemiring.unwrap_record().one.clone().unwrap() }))
}

pub fn Data_Semiring_Generic_genericOne_prime(mut dict: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
dict.unwrap_record().genericOne_prime.clone().unwrap()
}

pub fn Data_Semiring_Generic_genericOne(mut dictGeneric: crate::UnknownType, mut dictGenericSemiring: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericSemiring.unwrap_record().genericOne_prime.clone().unwrap())
}

pub fn Data_Semiring_Generic_genericMul_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericMul_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Semiring_Generic_genericMul(mut dictGeneric: crate::UnknownType, mut dictGenericSemiring: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring.unwrap_record().genericMul_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)))
}

pub fn Data_Semiring_Generic_genericAdd_prime(mut a0: crate::UnknownType, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Accessor(Local(...)))))
(((/* Typed Abs */std::rc::Rc::new(move |mut dict: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>> {
    std::rc::Rc::new({ let _f = (dict.unwrap_record().genericAdd_prime.clone().unwrap()).unwrap_func(); move |mut _a: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> { std::rc::Rc::new({ let _f = (_f(_a)).unwrap_func(); move |mut _a: crate::UnknownType| -> crate::UnknownType { _f(_a) } }) } })
}))(a0.clone()))(a1.clone()))(a2.clone())
}

pub fn Data_Semiring_Generic_genericSemiringConstructor(mut dictGenericSemiring: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Lit)))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semiring_Generic::Dict_GenericSemiring { genericAdd_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    /* Typed Abs */{
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring.clone().unwrap_record().genericAdd_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericZero_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericSemiring.unwrap_record().genericZero_prime.clone().unwrap(), genericMul_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    /* Typed Abs */{
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring.clone().unwrap_record().genericMul_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v.clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */v1)
})
}
}), genericOne_prime: /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */dictGenericSemiring.unwrap_record().genericOne_prime.clone().unwrap() }))
}

pub fn Data_Semiring_Generic_genericSemiringProduct(mut dictGenericSemiring: crate::UnknownType, mut dictGenericSemiring1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Lit)))))))
crate::Value::Class(std::rc::Rc::new(crate::Purs_Data_Semiring_Generic::Dict_GenericSemiring { genericAdd_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut dictGenericSemiring1 = dictGenericSemiring1.clone();
    /* Typed Abs */{
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut dictGenericSemiring1 = dictGenericSemiring1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut dictGenericSemiring1 = dictGenericSemiring1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring.clone().unwrap_record().genericAdd_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring1.clone().unwrap_record().genericAdd_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
})
}
}), genericZero_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![dictGenericSemiring.unwrap_record().genericZero_prime.clone().unwrap(), dictGenericSemiring1.unwrap_record().genericZero_prime.clone().unwrap()])), ..Default::default() })), genericMul_prime: /* Typed Abs */std::rc::Rc::new(move |mut v: crate::UnknownType| -> std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType> {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut dictGenericSemiring1 = dictGenericSemiring1.clone();
    /* Typed Abs */{
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut dictGenericSemiring1 = dictGenericSemiring1.clone();
    std::rc::Rc::new(move |mut v1: crate::UnknownType| -> crate::UnknownType {
    let mut dictGenericSemiring = dictGenericSemiring.clone();
    let mut dictGenericSemiring1 = dictGenericSemiring1.clone();
    let mut v = v.clone();
    /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring.clone().unwrap_record().genericMul_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[0].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.clone().unwrap_record().vals.as_ref().unwrap()[0].clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring1.clone().unwrap_record().genericMul_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v.clone().unwrap_record().vals.as_ref().unwrap()[1].clone())).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */v1.unwrap_record().vals.as_ref().unwrap()[1].clone())])), ..Default::default() }))
})
}
}), genericOne_prime: /* Typed crate::UnknownType <- crate::UnknownType : CtorSaturated(...) */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { tag: "Product", vals: Some(std::rc::Rc::new(vec![dictGenericSemiring.unwrap_record().genericOne_prime.clone().unwrap(), dictGenericSemiring1.unwrap_record().genericOne_prime.clone().unwrap()])), ..Default::default() })) }))
}

pub fn Data_Semiring_Generic_genericAdd(mut dictGeneric: crate::UnknownType, mut dictGenericSemiring: crate::UnknownType, mut x: crate::UnknownType, mut y: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Accessor(Local(...))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().to.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((dictGenericSemiring.unwrap_record().genericAdd_prime.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.clone().unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */x))).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */(dictGeneric.unwrap_record().from.clone().unwrap()).unwrap_func()(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */y)))
}





