#![allow(warnings)]
use perceus_ptr::PerceusPtr;
use purust_core::*;


// Code generated by purust for module Spago_Generated_BuildInfo



pub fn Spago_Generated_BuildInfo_spagoVersion() -> String {
    // AST: Typed(Typed(Lit))
/* Typed String <- String : Lit */String::from(r#"1.0.3"#)
}

pub fn Spago_Generated_BuildInfo_pursVersion() -> String {
    // AST: Typed(Typed(Lit))
/* Typed String <- String : Lit */String::from(r#"0.15.16"#)
}

pub fn Spago_Generated_BuildInfo_packages() -> crate::UnknownType {
    // AST: Typed(Typed(Lit))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { purust_minus_hello_minus_world: Some(crate::mk_string(&(/* Typed String <- String : Lit */String::from(r#"0.0.0"#)))), ..Default::default() }))
}





